name: Building Dump

on: [push]

env:
  ROM_URL: https://tdrive.elytra8.workers.dev/DerpFest-11-Official-Alpha-sakura-20210124-0630.zip
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumper Source Code
         run: git clone https://github.com/SuperCosmicBeing/dumper
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh

       - name: Download Stock Rom & Generate dump
         run: |
              cd dumper
              sudo bash dumpyara.sh $ROM_URL ${{ secrets.GHTOKEN }}
       
      
    
